"""Add foreign key constraints for tenant_id

Revision ID: 1f7f8d18be67
Revises: 6dbc28808377
Create Date: 2025-10-19 22:10:29.887897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7f8d18be67'
down_revision = '6dbc28808377'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_log', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'channel', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'contact_map', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'deal_link', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'dialog', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'message', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'routing_rule', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'user', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'webhook_event', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_event', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'routing_rule', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'dialog', type_='foreignkey')
    op.drop_constraint(None, 'deal_link', type_='foreignkey')
    op.drop_constraint(None, 'contact_map', type_='foreignkey')
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    # ### end Alembic commands ###
