"""Add username field to user table

Revision ID: 6dbc28808377
Revises: 0001
Create Date: 2025-10-19 22:08:27.175173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dbc28808377'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'audit_log', 'user', ['actor_user_id'], ['id'])
    op.add_column('channel', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('channel', 'metadata')
    op.create_index(op.f('ix_contact_map_tenant_id'), 'contact_map', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_deal_link_tenant_id'), 'deal_link', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dialog_tenant_id'), 'dialog', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'dialog', 'channel', ['channel_id'], ['id'])
    op.create_index(op.f('ix_message_tenant_id'), 'message', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'message', 'dialog', ['dialog_id'], ['id'])
    op.add_column('user', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_webhook_event_tenant_id'), 'webhook_event', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_tenant_id'), table_name='webhook_event')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'username')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_index(op.f('ix_message_tenant_id'), table_name='message')
    op.drop_constraint(None, 'dialog', type_='foreignkey')
    op.drop_index(op.f('ix_dialog_tenant_id'), table_name='dialog')
    op.drop_index(op.f('ix_deal_link_tenant_id'), table_name='deal_link')
    op.drop_index(op.f('ix_contact_map_tenant_id'), table_name='contact_map')
    op.add_column('channel', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('channel', 'meta')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    # ### end Alembic commands ###
